AllCops:
  TargetRubyVersion: 2.2

# generic rules
Metrics/LineLength:
  Enabled: false
Naming/FileName:
  Enabled: false

# specific project rules
Lint/InterpolationCheck:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
# Metrics/BlockLength:
#   Enabled: false
# Metrics/ClassLength:
#   Enabled: false
# Metrics/CyclomaticComplexity:
#   Max: 10
Metrics/MethodLength:
  Enabled: false
# Metrics/PerceivedComplexity:
#   Enabled: false
# Style/IfInsideElse:
#   Enabled: false
# Style/RescueModifier:
#   Enabled: false
# Style/ClassVars:
#   Enabled: false
Security/Eval:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $config
    - $config_file
